openapi: 3.1.0
info:
  title: Workspace Organizer API
  version: 0.1.0
  description: Generated slice documenting the workspace collection endpoint.
paths:
  /api/v1/workspaces:
    get:
      summary: List workspaces
      operationId: listWorkspaces
      tags:
        - Workspaces
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
          required: false
          description: 1-indexed page number. Defaults to 1 when omitted.
        - in: query
          name: pageSize
          schema:
            type: integer
            minimum: 1
            maximum: 100
          required: false
          description: Number of items per page. Defaults to 20.
      responses:
        '200':
          description: Paginated collection of workspace summaries.
          content:
            application/json:
              schema:
                $ref: '../schemas/workspaces/WorkspaceListResponse.yaml'
        '400':
          description: Invalid pagination parameters.
          content:
            application/json:
              schema:
                $ref: '../schemas/common/ErrorPayload.yaml'
components:
  securitySchemes: {}
